package tablas;
// Generated 12 dic 2022 11:10:18 by Hibernate Tools 5.6.12.Final

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private ClientesId id;

	public Clientes() {
	}

	public Clientes(ClientesId id) {
		this.id = id;
	}

	public ClientesId getId() {
		return this.id;
	}

	public void setId(ClientesId id) {
		this.id = id;
	}

}
