package com.modelo;

// default package
// Generated 6 feb 2023 11:51:31 by Hibernate Tools 5.6.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Necesitado generated by hbm2java
 */
public class Necesitado implements java.io.Serializable {

	private int id;
	private String nombre;
	private String apellido;
	private int edad;
	private String sexo;
	private String estadoCivil;
	private String necesidades;
	private Set necesidads = new HashSet(0);

	public Necesitado() {
	}

	public Necesitado(int id, String nombre, String apellido, int edad, String sexo, String estadoCivil,
			String necesidades) {
		this.id = id;
		this.nombre = nombre;
		this.apellido = apellido;
		this.edad = edad;
		this.sexo = sexo;
		this.estadoCivil = estadoCivil;
		this.necesidades = necesidades;
	}

	public Necesitado(int id, String nombre, String apellido, int edad, String sexo, String estadoCivil,
			String necesidades, Set necesidads) {
		this.id = id;
		this.nombre = nombre;
		this.apellido = apellido;
		this.edad = edad;
		this.sexo = sexo;
		this.estadoCivil = estadoCivil;
		this.necesidades = necesidades;
		this.necesidads = necesidads;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public String getNecesidades() {
		return this.necesidades;
	}

	public void setNecesidades(String necesidades) {
		this.necesidades = necesidades;
	}

	public Set getNecesidads() {
		return this.necesidads;
	}

	public void setNecesidads(Set necesidads) {
		this.necesidads = necesidads;
	}

}
