package com.modelo;
// Generated 13 feb 2023 11:00:08 by Hibernate Tools 5.6.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Voluntario generated by hbm2java
 * @author Alvaro
 *
 */
public class Voluntario implements java.io.Serializable {

	private int id;
	private String nombre;
	private String apellido;
	private int edad;
	private String sexo;
	private String estadoCivil;
	private String disponibilidad;
	private Set necesidads = new HashSet(0);

	public Voluntario() {
	}

	public Voluntario(int id, String nombre, String apellido, int edad, String sexo, String estadoCivil,
			String disponibilidad) {
		this.id = id;
		this.nombre = nombre;
		this.apellido = apellido;
		this.edad = edad;
		this.sexo = sexo;
		this.estadoCivil = estadoCivil;
		this.disponibilidad = disponibilidad;
	}

	public Voluntario(int id, String nombre, String apellido, int edad, String sexo, String estadoCivil,
			String disponibilidad, Set necesidads) {
		this.id = id;
		this.nombre = nombre;
		this.apellido = apellido;
		this.edad = edad;
		this.sexo = sexo;
		this.estadoCivil = estadoCivil;
		this.disponibilidad = disponibilidad;
		this.necesidads = necesidads;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public String getDisponibilidad() {
		return this.disponibilidad;
	}

	public void setDisponibilidad(String disponibilidad) {
		this.disponibilidad = disponibilidad;
	}

	public Set getNecesidads() {
		return this.necesidads;
	}

	public void setNecesidads(Set necesidads) {
		this.necesidads = necesidads;
	}

}
